### ISSUE TITLE
No log info? 

### ISSUE THREAD

**Issue by MrScruffles** [neurondevelopment/StoreBot#1]
Hey, idk if you still work on this project but I have been getting no logs in my channel for purchases idk if I placed them or If I did something out of the ordinary. 

"logs": {
"commandLogs": "--"  <-- a channel id
"paymentLogs": "--" <--  a channel id

If you can help me it would be much appreciated

**Comment by ThomasCreasey** [comment]
Hello, 

The logging system should be working fine, are you getting any errors in your console? 

Nothing has changed that would make it not send logs, unless perhaps the bot doesn't have permissions to send messages in the channel
